apiVersion: v1
kind: Secret
metadata:
  name: secret-creds
data:
  username: surendharramaraj



spec:
  containers:
    - image: ""
      name: mysql
      env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef: 
              name: secret-creds
              key : username
